name: preventivemaintenanceapp
description: Preventive maintenance checklist and equipment management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.2.0
  intl: ^0.19.0

  # Firebase Core Services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.2.1
  firebase_messaging: ^15.1.3

  # Connectivity + utils
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4

  # Models/serialization (aligned stable versions)
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Use stable Freezed builder compatible with build_runner
  freezed: ^2.5.2
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
    - assets/icons/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
