// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuWCQdG5Xk5c1UqkvsTYFBmyPY8oEtbW8',
    appId: '1:958316881923:web:a23e5efd19ddc7f5868636',
    messagingSenderId: '958316881923',
    projectId: 'preventive-maintenance-430c5',
    authDomain: 'preventive-maintenance-430c5.firebaseapp.com',
    storageBucket: 'preventive-maintenance-430c5.firebasestorage.app',
    measurementId: 'G-7Q9G2EKH2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY6MWri0SfRRovgp4xvDRbXAFSbEVZXnc',
    appId: '1:958316881923:android:89e9af6de17837f7868636',
    messagingSenderId: '958316881923',
    projectId: 'preventive-maintenance-430c5',
    storageBucket: 'preventive-maintenance-430c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLaROkYjFlaK2szEVXa2PEvGlooF6m2w',
    appId: '1:958316881923:ios:f2a5e86f7933b0e6868636',
    messagingSenderId: '958316881923',
    projectId: 'preventive-maintenance-430c5',
    storageBucket: 'preventive-maintenance-430c5.firebasestorage.app',
    iosBundleId: 'com.example.preventivemaintenanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJLaROkYjFlaK2szEVXa2PEvGlooF6m2w',
    appId: '1:958316881923:ios:f2a5e86f7933b0e6868636',
    messagingSenderId: '958316881923',
    projectId: 'preventive-maintenance-430c5',
    storageBucket: 'preventive-maintenance-430c5.firebasestorage.app',
    iosBundleId: 'com.example.preventivemaintenanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuWCQdG5Xk5c1UqkvsTYFBmyPY8oEtbW8',
    appId: '1:958316881923:web:06c47b3988076464868636',
    messagingSenderId: '958316881923',
    projectId: 'preventive-maintenance-430c5',
    authDomain: 'preventive-maintenance-430c5.firebaseapp.com',
    storageBucket: 'preventive-maintenance-430c5.firebasestorage.app',
    measurementId: 'G-MKR54FP23L',
  );
}
